export enum TipoNotificacao {
  SEGUIR_USUARIO = "SEGUIR_USUARIO",
  CURTIR_RECEITA = "CURTIR_RECEITA",
  COMENTAR_RECEITA = "COMENTAR_RECEITA",
  COMENTAR_CHECKIN = "COMENTAR_CHECKIN",
  RANKING_COMPETICAO = "RANKING_COMPETICAO",
}
