export enum TipoNotificacao {
    NOVO_SEGUIDOR = "NOVO_SEGUIDOR",
    CURTIDA_RECEITA = "CURTIDA_RECEITA",
    COMENTARIO_RECEITA = "COMENTARIO_RECEITA",
    COMENTARIO_CHECKIN = "COMENTARIO_CHECKIN",
    ATUALIZACAO_RANKING = "ATUALIZACAO_RANKING"
}
